cmake_minimum_required(VERSION 3.26.1)

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)

set(TOOLCHAIN_PATH "${PROJECT_SOURCE_DIR}/tools/mingw/bin")
set(TOOLCHAIN_PREFIX ${TOOLCHAIN_PATH}/i686-w64-mingw32-)

set(CMAKE_C_COMPILER    ${TOOLCHAIN_PREFIX}gcc.exe)
set(CMAKE_ASM_COMPILER  ${CMAKE_C_COMPILER})
set(CMAKE_OBJCOPY       ${TOOLCHAIN_PATH}/objcopy.exe)
set(CMAKE_SIZE_UTIL     ${TOOLCHAIN_PATH}/size.exe)
set(CMAKE_GCOV          ${TOOLCHAIN_PATH}/gcov.exe)

set(CMAKE_FIND_ROOT_PATH  ${TOOLCHAIN_PATH}/../)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
